version: '3.8'
services:

  postgres:
    build: ./dev/postgres  # building custom image to add pgvector extension
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
      - ./dev/postgres/init.sql:/docker-entrypoint-initdb.d/init_1.sql  # for init script
    env_file:
      - dev/configs/postgres.env

  baddie:
    build: .
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - postgres
    env_file:
      - dev/configs/postgres.env
      - dev/configs/aws.env

volumes:
  postgres-data:

# Below is the configuration for using an existing docker network instead of the letting docker-compose create one by default. I use an external network to handle routing and deployment of multiple docker compose stacks on same server using traefik (https://github.com/traefik/traefik).
# While running this docker-compose, you have 2 options
#   1. Comment out the below 4 lines, and run this stack as usual, with `docker-compose up`
#   2. Create a docker network with name `traefik` using command `docker network create traefik`, and move onto better things in your life.
networks:
  default:
    name: traefik
    external: true